envName: stg
namespace: acme-app-stg
components:
  frontend:
    replicaCount: 2
    image: { tag: "latest" }      # ← Jenkins(CI) 가 커밋으로 갱신
  backend:
    replicaCount: 2
    image: { tag: "latest" }      # ← Jenkins(CI) 가 커밋으로 갱신
    env:
      - { name: APP_ENV, value: "stg" }
