# ArgoCD Application (test)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acme-app-test
  namespace: argocd
spec:
  project: acme-test
  source:
    repoURL: https://<GITEA_IP>/admin/acme-gitops.git
    targetRevision: main
    path: helm/acme-app
    helm:
      valueFiles: [ values-test.yaml ]
  destination:
    server: https://kubernetes.default.svc
    namespace: acme-app-test
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
